version: '3.9'

services:
  db:
    image: library/postgres:14
    ports:
      - "5432:5432"
    volumes:
      - "./ddl:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: password
