version: '3.8'

services:
  db:
    image: library/postgres:12.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
